behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 8192  # Increased from 4096 (optional based on memory)
      buffer_size: 40960  # Increased from 20480
      learning_rate: 0.0003
      beta: 0.01  # Increased from 0.005 to promote exploration
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4  # Increased from 3 for better gradient estimates
      learning_rate_schedule: linear  # Changed from 'constant' to 'linear'
    network_settings:
      normalize: true  # Enabled normalization for input stability
      hidden_units: 1024  # Increased from 512
      num_layers: 3  # Increased from 2
      vis_encode_type: simple
      inference_device: gpu
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 10000
      team_change: 200000
      swap_steps: 2000
      window: 20  # Increased from 10 to include more opponents
      play_against_latest_model_ratio: 0.7  # Increased from 0.5
      initial_elo: 1200.0
    # Optional: Add intrinsic reward signal
    # reward_signals:
    #   intrinsic:
    #     gamma: 0.99
    #     strength: 0.01
    #     curiosity_strength: 0.1
